-- First-stage Instagram/Manus pipeline
create table if not exists public.instagram_posts (
  id bigint generated by default as identity primary key,
  status text not null default 'pending'
    check (status in ('pending','manus_processing','ready','publishing','published','error')),
  category text,
  manus_task_id text unique,
  manus_task_url text,
  prompt text,
  caption text,
  assets jsonb,
  manus_result jsonb,
  instagram_media_id text,
  source_chat_id text,
  source_message_id bigint,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.instagram_post_products (
  id bigint generated by default as identity primary key,
  instagram_post_id bigint not null references public.instagram_posts(id) on delete cascade,
  produto_fila_id bigint not null references public.produtos_fila(id) on delete cascade,
  position integer not null check (position > 0),
  product_snapshot jsonb,
  created_at timestamptz not null default now(),
  unique (instagram_post_id, produto_fila_id),
  unique (instagram_post_id, position)
);

create index if not exists idx_instagram_posts_status
  on public.instagram_posts(status);

create index if not exists idx_instagram_post_products_produto
  on public.instagram_post_products(produto_fila_id);

alter table public.instagram_posts enable row level security;
alter table public.instagram_post_products enable row level security;

revoke all on public.instagram_posts from anon, authenticated;
revoke all on public.instagram_post_products from anon, authenticated;
